apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-scheduler-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/binding", "nodes"]
    verbs: ["get", "list", "watch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-scheduler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-scheduler-role
subjects:
  - kind: ServiceAccount
    name: custom-scheduler-sa
